### ISSUE TITLE
FrontEnd: Make the page mobile friendly.

### ISSUE THREAD

**Issue by drex44** [drex44/demo-site-awesome-react-links#1]
This site is in react and is created using create-react-app.

Currently, it is for desktop only. so make some changes to the site so it looks good on mobile also.

**Comment by Visovsiouk** [comment]
@drex44 Can I try my hand on this?

**Comment by drex44** [comment]
yeah, go ahead. if you need any help, ask me anything. :+1:

**Comment by Apoorva-13** [comment]
can I work on this too?

**Comment by drex44** [comment]
Hi, @Apoorva-13 it seems @Visovsiouk is already working on this one. it would be waste of your efforts. you can work on another issue #2

**Comment by ghost** [comment]
@Visovsiouk How is it going? Do you need any help/support?

**Comment by drex44** [comment]
@Visovsiouk are you working on this?

**Comment by Visovsiouk** [comment]
@drex44 @jrdevforlife Haven't started yet but I'll get it done by the end of the week.

**Comment by ghost** [comment]
@Visovsiouk If you need some assistance, let me know.
