### ISSUE TITLE
FrontEnd: Add github stars below heading

### ISSUE THREAD

**Issue by drex44** [drex44/demo-site-awesome-react-links#10]
checkout the live website URL in the readme.
This is the demo site of an npm package awesome-react-links. this site is built in react.

please use GitHub API to fetch the stars from GitHub and show it. 
Note: it should fetch the stars of this repository,
http://github.com/drex44/awesome-react-links

**Comment by Robbatron** [comment]
This one sounds fun as well. Are you assigning these out? I don't want to duplicate work.

**Comment by drex44** [comment]
@Robbatron you can work on this one if you want to. I will assign it to you.

**Comment by andrasbacsai** [comment]
I can do it aswell, if it's still available.

**Comment by euconectei** [comment]
PR

**Comment by Robbatron** [comment]
I was going to work on this tonight but it looks like @euconectei has submitted the PR.
