### ISSUE TITLE
FrontEnd: create a footer

### ISSUE THREAD

**Issue by drex44** [drex44/demo-site-awesome-react-links#11]
Check out the website link in the readme. The site is in ReactJS. It is the demo and documentation site for the NPM package awesome-react-links.

Todo,
create a footer.js component with website title in the middle.
I will add links such as about, contributors etc once it completed.

Comment if you need any help!

**Comment by Robbatron** [comment]
I might be able to take this...You just want a simple rectangular footer with the centered text `https://awesome-react-links.surge.sh/`? The same color as the header?

**Comment by drex44** [comment]
yes, the footer should have the same color as the header. the text in the middle should have **Awesome React Links**.
