### ISSUE TITLE
FrontEnd: create a react component to show contributors

### ISSUE THREAD

**Issue by drex44** [drex44/demo-site-awesome-react-links#12]
Check out the website link in the readme. The site is in ReactJS. It is the demo and documentation site for the NPM package awesome-react-links.

Todo,
Fetch the contributors from this repo and http://github.com/drex44/awesome-react-links repo using GitHub API.
show this information in a new component called contributors.js.
Use this component at the end in App.js to show contributors.

Comment if you need any help!

**Comment by hirotachi** [comment]
permission to go for it.

**Comment by hirotachi** [comment]
#14 check this out :P
