### ISSUE TITLE
FrontEnd: make a button to copy code snippet

### ISSUE THREAD

**Issue by drex44** [drex44/demo-site-awesome-react-links#2]
The site is in React and it is available on [here](https://awesome-react-links.surge.sh).

It shows the code snippets on the right-hand side. It is a reusable component. 
In this component, Add a button to copy the given code snippet just like many amazing UI libraries have.

If you have any doubts, comment below!

**Comment by Apoorva-13** [comment]
can i work on this?

**Comment by drex44** [comment]
yeah sure! go ahead.

**Comment by Apoorva-13** [comment]
I feel we can use the package [(https://www.npmjs.com/package/react-copy-to-clipboard) ]here.
Am I correct ,pls guide me ,I am new to this.

**Comment by altany** [comment]
Working on it without a package as this is a fairly simple task

**Comment by drex44** [comment]
@Apoorva-13 the component is already there and you have to merge it there so as long as the website works it's okay to use any package. you simply have to add a button at the top corner of the div which copies the code.

**Comment by drex44** [comment]
@Apoorva-13 you can submit the PR, I will review it and merge it. however, create a separate pluggable component so it can be reused elsewhere also.

**Comment by drex44** [comment]
@altany and @Apoorva-13, check your site locally and then submit PR. I will merge them. 
develop the copyToClipboard component reusable and pluggable to keep the code modular.

**Comment by altany** [comment]
@drex44 I just sent a PR. Luckily I created as a separate pluggable plugin, as you suggested, and also added it to your page. Hope it is what you had in mind and you approve :)

**Comment by drex44** [comment]
@Apoorva-13, are you still working on this?

**Comment by Apoorva-13** [comment]
No I am not working working on this.

**Comment by drex44** [comment]
okay @Apoorva-13, then I will close this issue!
