### ISSUE TITLE
FrontEnd: Make the copy button intuitive!

### ISSUE THREAD

**Issue by drex44** [drex44/demo-site-awesome-react-links#4]
Check out the live website.
http://awesome-react-links.surge.sh
The website is in react.

It has a copy button next to the code snippet. make it more intuitive and beautiful.

**Comment by ghost** [comment]
@drex44 Can't seem to find that copy button on the production site. Am I just blind or is it gone?

**Comment by drex44** [comment]
@jrdevforlife sorry, please check again!

**Comment by ghost** [comment]
Now I can see it. 👍 Will check what I can do here.

**Comment by drex44** [comment]
Thanks @jrdevforlife

**Comment by hex2f** [comment]
Can i try aswell? I have some ideas :)

**Comment by ghost** [comment]
@RekkyRek Sure, go ahead. Make sure to post some screenshots.

**Comment by ghost** [comment]
I came up with a simple solution, nothing fancy. I went with your current "color scheme". It's easy to change later on tho. 

![copy-code-button](https://user-images.githubusercontent.com/1422640/46539914-19f7ad80-c8b8-11e8-96bb-551d60c625e9.jpg)

@drex44 @RekkyRek

**Comment by drex44** [comment]
Great Job man!. PR merged! :+1:
